// Persistence Of Vision raytracer version 1.0 sample file.

#declare light1 = color red 0.1 green 0.1 blue 0.1
#declare light2 = color red 0.2 green 0.2 blue 0.2
#declare light3 = color red 0.3 green 0.3 blue 0.3
#declare light4 = color red 0.4 green 0.4 blue 0.4
#declare light5 = color red 0.5 green 0.5 blue 0.5

#declare light1 = object { light_source { <0.0 0.0 0.0> color light1 }  }
#declare light2 = object { light_source { <0.0 0.0 0.0> color light2 }  }
#declare light3 = object { light_source { <0.0 0.0 0.0> color light3 }  }
#declare light4 = object { light_source { <0.0 0.0 0.0> color light4 }  }
#declare light5 = object { light_source { <0.0 0.0 0.0> color light5 }  }

