// Persistence Of Vision raytracer version 1.0 sample file.

/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 9.500000
      Minor radius: 0.500000
      Outer radius: 10.000000
      Inner radius: 9.000000
   ------------------------------------------------------------------------------
*/

#declare torus =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -181.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   180.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -181.000000 0.000000 8100.000000 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 9.376883
      Minor radius: 0.500000
      Outer radius: 9.876883
      Inner radius: 8.876883
   ------------------------------------------------------------------------------
*/

#declare torus00 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -176.351870
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   175.351870 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -176.351870 0.000000 7687.069542 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 9.010565
      Minor radius: 0.500000
      Outer radius: 9.510565
      Inner radius: 8.510565
   ------------------------------------------------------------------------------
*/

#declare torus01 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -162.880563
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   161.880563 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -162.880563 0.000000 6551.329189 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 8.410065
      Minor radius: 0.500000
      Outer radius: 8.910065
      Inner radius: 7.910065
   ------------------------------------------------------------------------------
*/

#declare torus02 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -141.958387
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   140.958387 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -141.958387 0.000000 4967.316689 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 7.590170
      Minor radius: 0.500000
      Outer radius: 8.090170
      Inner radius: 7.090170
   ------------------------------------------------------------------------------
*/

#declare torus03 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -115.721361
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   114.721361 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -115.721361 0.000000 3290.247682 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 6.571068
      Minor radius: 0.500000
      Outer radius: 7.071068
      Inner radius: 6.071068
   ------------------------------------------------------------------------------
*/

#declare torus04 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -86.857869
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   85.857869 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -86.857869 0.000000 1842.893431 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 5.377853
      Minor radius: 0.500000
      Outer radius: 5.877853
      Inner radius: 4.877853
   ------------------------------------------------------------------------------
*/

#declare torus05 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -58.342606
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   57.342606 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -58.342606 0.000000 822.043609 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 4.039905
      Minor radius: 0.500000
      Outer radius: 4.539905
      Inner radius: 3.539905
   ------------------------------------------------------------------------------
*/

#declare torus06 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -33.141665
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   32.141665 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -33.141665 0.000000 258.271654 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 2.590170
      Minor radius: 0.500000
      Outer radius: 3.090170
      Inner radius: 2.090170
   ------------------------------------------------------------------------------
*/

#declare torus07 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -13.917961
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   12.917961 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -13.917961 0.000000 41.718431 >
   sturm
}
/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 1.064345
      Minor radius: 0.500000
      Outer radius: 1.564345
      Inner radius: 0.564345
   ------------------------------------------------------------------------------
*/

#declare torus08 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -2.765661
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   1.765661 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -2.765661 0.000000 0.779389 >
   sturm
}

/*
   ------------------------------------------------------------------------------
   This DAT file created by Truman's Torus Generator 1.0 (c) 1991 Truman Brown
   ------------------------------------------------------------------------------
   Torus specs:
      Major radius: 9.500000
      Minor radius: 0.200000
      Outer radius: 9.700000
      Inner radius: 9.300000
   ------------------------------------------------------------------------------
*/

#declare torus09 =
quartic {
   <    1.000000 0.000000 0.000000 0.000000 2.000000
   0.000000 0.000000 2.000000 0.000000 -180.580000
   0.000000 0.000000 0.000000 0.000000 0.000000
   0.000000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 0.000000 2.000000 0.000000
   180.420000 0.000000 0.000000 0.000000 0.000000
   1.000000 0.000000 -180.580000 0.000000 8137.844100 >
   sturm
}
/*
declare torus  = object quartic TORUS   end_quartic bounded_by intersection sphere <0 0 0> 10.1 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus0 = object quartic TORUS00 end_quartic bounded_by intersection sphere <0 0 0>  9.9 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus1 = object quartic TORUS01 end_quartic bounded_by intersection sphere <0 0 0>  9.6 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus2 = object quartic TORUS02 end_quartic bounded_by intersection sphere <0 0 0>  9.0 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus3 = object quartic TORUS03 end_quartic bounded_by intersection sphere <0 0 0>  8.1 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus4 = object quartic TORUS04 end_quartic bounded_by intersection sphere <0 0 0>  7.1 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus5 = object quartic TORUS05 end_quartic bounded_by intersection sphere <0 0 0>  5.9 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus6 = object quartic TORUS06 end_quartic bounded_by intersection sphere <0 0 0>  4.6 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus7 = object quartic TORUS07 end_quartic bounded_by intersection sphere <0 0 0>  3.1 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus8 = object quartic TORUS08 end_quartic bounded_by intersection sphere <0 0 0>  1.6 end_sphere plane <0 1 0> 0.51 end_plane plane < 0 -1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus9 = object quartic TORUS09 end_quartic bounded_by intersection sphere <0 0 0>  9.8 end_sphere plane <0 1 0> 0.21 end_plane plane < 0 -1 0> 0.21 end_plane end_intersection end_bound end_object

declare torus  = object quartic TORUS   end_quartic bounded_by intersection sphere <0 0 0> 10.1 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus0 = object quartic TORUS00 end_quartic bounded_by intersection sphere <0 0 0>  9.9 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus1 = object quartic TORUS01 end_quartic bounded_by intersection sphere <0 0 0>  9.6 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus2 = object quartic TORUS02 end_quartic bounded_by intersection sphere <0 0 0>  9.0 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus3 = object quartic TORUS03 end_quartic bounded_by intersection sphere <0 0 0>  8.1 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus4 = object quartic TORUS04 end_quartic bounded_by intersection sphere <0 0 0>  7.1 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus5 = object quartic TORUS05 end_quartic bounded_by intersection sphere <0 0 0>  5.9 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus6 = object quartic TORUS06 end_quartic bounded_by intersection sphere <0 0 0>  4.6 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus7 = object quartic TORUS07 end_quartic bounded_by intersection sphere <0 0 0>  3.1 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus8 = object quartic TORUS08 end_quartic bounded_by intersection sphere <0 0 0>  1.6 end_sphere plane <0 1 0> 0.51 end_plane end_intersection end_bound end_object
declare torus9 = object quartic TORUS09 end_quartic bounded_by intersection sphere <0 0 0>  9.8 end_sphere plane <0 1 0> 0.21 end_plane end_intersection end_bound end_object
*/

#declare torus  = object { quartic { torus    } bounded_by { sphere { <0 0 0> 10.1  }  }  }
#declare torus0 = object { quartic { torus00  } bounded_by { sphere { <0 0 0>  9.9  }  }  }
#declare torus1 = object { quartic { torus01  } bounded_by { sphere { <0 0 0>  9.6  }  }  }
#declare torus2 = object { quartic { torus02  } bounded_by { sphere { <0 0 0>  9.0  }  }  }
#declare torus3 = object { quartic { torus03  } bounded_by { sphere { <0 0 0>  8.1  }  }  }
#declare torus4 = object { quartic { torus04  } bounded_by { sphere { <0 0 0>  7.1  }  }  }
#declare torus5 = object { quartic { torus05  } bounded_by { sphere { <0 0 0>  5.9  }  }  }
#declare torus6 = object { quartic { torus06  } bounded_by { sphere { <0 0 0>  4.6  }  }  }
#declare torus7 = object { quartic { torus07  } bounded_by { sphere { <0 0 0>  3.1  }  }  }
#declare torus8 = object { quartic { torus08  } bounded_by { sphere { <0 0 0>  1.6  }  }  }
#declare torus9 = object { quartic { torus09  } bounded_by { sphere { <0 0 0>  9.8  }  }  }
