# --- DOUBLE ---

#
# clean up
#
rm -f tmp/*

#
# run tests
#
./t4 -sv tbo/tbo/fpdup__db.tbo         inp/inp/fpu_1db.bin tmp/fpdup__db.sim  #1800
./t4 -sv tbo/tbo/fprev__db.tbo         inp/inp/fpu_1db.bin tmp/fprev__db.sim  #1800
./t4 -sv tbo/tbo/fpurn__db.tbo         inp/inp/fpu_1db.bin tmp/fpurn__db.sim  #1800
./t4 -sv tbo/tbo/fpurz__db.tbo         inp/inp/fpu_1db.bin tmp/fpurz__db.sim  #1800
./t4 -sv tbo/tbo/fpurp__db.tbo         inp/inp/fpu_1db.bin tmp/fpurp__db.sim  #1800
./t4 -sv tbo/tbo/fpurm__db.tbo         inp/inp/fpu_1db.bin tmp/fpurm__db.sim  #1800
./t4 -sv tbo/tbo/fpadd__db.tbo         inp/inp/fpu_2db.bin tmp/fpadd__db.sim  #C0000
./t4 -sv tbo/tbo/fpsub__db.tbo         inp/inp/fpu_2db.bin tmp/fpsub__db.sim  #C0000
./t4 -sv tbo/tbo/fpmul__db.tbo         inp/inp/fpu_2db.bin tmp/fpmul__db.sim  #C0000
./t4 -sv tbo/tbo/fpdiv__db.tbo         inp/inp/fpu_2db.bin tmp/fpdiv__db.sim  #C0000
./t4 -sv tbo/tbo/fpuabs__db.tbo        inp/inp/fpu_1db.bin tmp/fpuabs__db.sim  #1800
./t4 -sv tbo/tbo/fpumulby2__db.tbo     inp/inp/fpu_1db.bin tmp/fpumulby2__db.sim  #1800
./t4 -sv tbo/tbo/fpudivby2__db.tbo     inp/inp/fpu_1db.bin tmp/fpudivby2__db.sim  #1800
./t4 -sv tbo/tbo/fpuexpinc32__db.tbo   inp/inp/fpu_1db.bin tmp/fpuexpinc32__db.sim  #1800
./t4 -sv tbo/tbo/fpuexpdec32__db.tbo   inp/inp/fpu_1db.bin tmp/fpuexpdec32__db.sim  #1800
./t4 -sv tbo/tbo/fpchkerr__db.tbo      inp/inp/fpu_1db.bin tmp/fpchkerr__db.sim  #1800
./t4 -sv tbo/tbo/fptesterr__db.tbo     inp/inp/fpu_1db.bin tmp/fptesterr__db.sim  #1800
./t4 -sv tbo/tbo/fpuseterr__db.tbo     inp/inp/fpu_1db.bin tmp/fpuseterr__db.sim  #1800
./t4 -sv tbo/tbo/fpuclrerr__db.tbo     inp/inp/fpu_1db.bin tmp/fpuclrerr__db.sim  #1800
./t4 -sv tbo/tbo/fpgt__db.tbo          inp/inp/fpu_2db.bin tmp/fpgt__db.sim  #C0000
./t4 -sv tbo/tbo/fpeq__db.tbo          inp/inp/fpu_2db.bin tmp/fpeq__db.sim  #C0000
./t4 -sv tbo/tbo/fpordered__db.tbo     inp/inp/fpu_2db.bin tmp/fpordered__db.sim  #C0000
./t4 -sv tbo/tbo/fpnan__db.tbo         inp/inp/fpu_1db.bin tmp/fpnan__db.sim  #1800
./t4 -sv tbo/tbo/fpnotfinite__db.tbo   inp/inp/fpu_1db.bin tmp/fpnotfinite__db.sim  #1800
./t4 -sv tbo/tbo/fpint__db.tbo         inp/inp/fpu_1db.bin tmp/fpint__db.sim  #1800
./t4 -sv tbo/tbo/fpuchki32__db.tbo     inp/inp/fpu_1db.bin tmp/fpuchki32__db.sim  #1800
./t4 -sv tbo/tbo/fpuchki64__db.tbo     inp/inp/fpu_1db.bin tmp/fpuchki64__db.sim  #1800
./t4 -sv tbo/tbo/fprtoi32__db.tbo      inp/inp/fpu_1db.bin tmp/fprtoi32__db.sim  #1800
./t4 -sv tbo/tbo/fprem__db.tbo         inp/inp/fpu_2db.bin tmp/fprem__db.sim #C0000

./t4 -sv tbo/tbo/fpduprndb.tbo         inp/inp/fpu_1db.bin tmp/fpduprndb.sim  #1800
./t4 -sv tbo/tbo/fprevrndb.tbo         inp/inp/fpu_1db.bin tmp/fprevrndb.sim  #1800
./t4 -sv tbo/tbo/fpurnrndb.tbo         inp/inp/fpu_1db.bin tmp/fpurnrndb.sim  #1800
./t4 -sv tbo/tbo/fpurzrndb.tbo         inp/inp/fpu_1db.bin tmp/fpurzrndb.sim  #1800
./t4 -sv tbo/tbo/fpurprndb.tbo         inp/inp/fpu_1db.bin tmp/fpurprndb.sim  #1800
./t4 -sv tbo/tbo/fpurmrndb.tbo         inp/inp/fpu_1db.bin tmp/fpurmrndb.sim  #1800
./t4 -sv tbo/tbo/fpaddrndb.tbo         inp/inp/fpu_2db.bin tmp/fpaddrndb.sim  #C0000
./t4 -sv tbo/tbo/fpsubrndb.tbo         inp/inp/fpu_2db.bin tmp/fpsubrndb.sim  #C0000
./t4 -sv tbo/tbo/fpmulrndb.tbo         inp/inp/fpu_2db.bin tmp/fpmulrndb.sim  #C0000
./t4 -sv tbo/tbo/fpdivrndb.tbo         inp/inp/fpu_2db.bin tmp/fpdivrndb.sim  #C0000
./t4 -sv tbo/tbo/fpuabsrndb.tbo        inp/inp/fpu_1db.bin tmp/fpuabsrndb.sim  #1800
./t4 -sv tbo/tbo/fpumulby2rndb.tbo     inp/inp/fpu_1db.bin tmp/fpumulby2rndb.sim  #1800
./t4 -sv tbo/tbo/fpudivby2rndb.tbo     inp/inp/fpu_1db.bin tmp/fpudivby2rndb.sim  #1800
./t4 -sv tbo/tbo/fpuexpinc32rndb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpinc32rndb.sim  #1800
./t4 -sv tbo/tbo/fpuexpdec32rndb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpdec32rndb.sim  #1800
./t4 -sv tbo/tbo/fpchkerrrndb.tbo      inp/inp/fpu_1db.bin tmp/fpchkerrrndb.sim  #1800
./t4 -sv tbo/tbo/fptesterrrndb.tbo     inp/inp/fpu_1db.bin tmp/fptesterrrndb.sim  #1800
./t4 -sv tbo/tbo/fpuseterrrndb.tbo     inp/inp/fpu_1db.bin tmp/fpuseterrrndb.sim  #1800
./t4 -sv tbo/tbo/fpuclrerrrndb.tbo     inp/inp/fpu_1db.bin tmp/fpuclrerrrndb.sim  #1800
./t4 -sv tbo/tbo/fpgtrndb.tbo          inp/inp/fpu_2db.bin tmp/fpgtrndb.sim  #C0000
./t4 -sv tbo/tbo/fpeqrndb.tbo          inp/inp/fpu_2db.bin tmp/fpeqrndb.sim  #C0000
./t4 -sv tbo/tbo/fporderedrndb.tbo     inp/inp/fpu_2db.bin tmp/fporderedrndb.sim  #C0000
./t4 -sv tbo/tbo/fpnanrndb.tbo         inp/inp/fpu_1db.bin tmp/fpnanrndb.sim  #1800
./t4 -sv tbo/tbo/fpnotfiniterndb.tbo   inp/inp/fpu_1db.bin tmp/fpnotfiniterndb.sim  #1800
./t4 -sv tbo/tbo/fpintrndb.tbo         inp/inp/fpu_1db.bin tmp/fpintrndb.sim  #1800
./t4 -sv tbo/tbo/fpuchki32rndb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki32rndb.sim  #1800
./t4 -sv tbo/tbo/fpuchki64rndb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki64rndb.sim  #1800
./t4 -sv tbo/tbo/fprtoi32rndb.tbo      inp/inp/fpu_1db.bin tmp/fprtoi32rndb.sim  #1800

./t4 -sv tbo/tbo/fpduprzdb.tbo         inp/inp/fpu_1db.bin tmp/fpduprzdb.sim  #1800
./t4 -sv tbo/tbo/fprevrzdb.tbo         inp/inp/fpu_1db.bin tmp/fprevrzdb.sim  #1800
./t4 -sv tbo/tbo/fpurnrzdb.tbo         inp/inp/fpu_1db.bin tmp/fpurnrzdb.sim  #1800
./t4 -sv tbo/tbo/fpurzrzdb.tbo         inp/inp/fpu_1db.bin tmp/fpurzrzdb.sim  #1800
./t4 -sv tbo/tbo/fpurprzdb.tbo         inp/inp/fpu_1db.bin tmp/fpurprzdb.sim  #1800
./t4 -sv tbo/tbo/fpurmrzdb.tbo         inp/inp/fpu_1db.bin tmp/fpurmrzdb.sim  #1800
./t4 -sv tbo/tbo/fpaddrzdb.tbo         inp/inp/fpu_2db.bin tmp/fpaddrzdb.sim  #C0000
./t4 -sv tbo/tbo/fpsubrzdb.tbo         inp/inp/fpu_2db.bin tmp/fpsubrzdb.sim  #C0000
./t4 -sv tbo/tbo/fpmulrzdb.tbo         inp/inp/fpu_2db.bin tmp/fpmulrzdb.sim  #C0000
./t4 -sv tbo/tbo/fpdivrzdb.tbo         inp/inp/fpu_2db.bin tmp/fpdivrzdb.sim  #C0000
./t4 -sv tbo/tbo/fpuabsrzdb.tbo        inp/inp/fpu_1db.bin tmp/fpuabsrzdb.sim  #1800
./t4 -sv tbo/tbo/fpumulby2rzdb.tbo     inp/inp/fpu_1db.bin tmp/fpumulby2rzdb.sim  #1800
./t4 -sv tbo/tbo/fpudivby2rzdb.tbo     inp/inp/fpu_1db.bin tmp/fpudivby2rzdb.sim  #1800
./t4 -sv tbo/tbo/fpuexpinc32rzdb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpinc32rzdb.sim  #1800
./t4 -sv tbo/tbo/fpuexpdec32rzdb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpdec32rzdb.sim  #1800
./t4 -sv tbo/tbo/fpchkerrrzdb.tbo      inp/inp/fpu_1db.bin tmp/fpchkerrrzdb.sim  #1800
./t4 -sv tbo/tbo/fptesterrrzdb.tbo     inp/inp/fpu_1db.bin tmp/fptesterrrzdb.sim  #1800
./t4 -sv tbo/tbo/fpuseterrrzdb.tbo     inp/inp/fpu_1db.bin tmp/fpuseterrrzdb.sim  #1800
./t4 -sv tbo/tbo/fpuclrerrrzdb.tbo     inp/inp/fpu_1db.bin tmp/fpuclrerrrzdb.sim  #1800
./t4 -sv tbo/tbo/fpgtrzdb.tbo          inp/inp/fpu_2db.bin tmp/fpgtrzdb.sim  #C0000
./t4 -sv tbo/tbo/fpeqrzdb.tbo          inp/inp/fpu_2db.bin tmp/fpeqrzdb.sim  #C0000
./t4 -sv tbo/tbo/fporderedrzdb.tbo     inp/inp/fpu_2db.bin tmp/fporderedrzdb.sim  #C0000
./t4 -sv tbo/tbo/fpnanrzdb.tbo         inp/inp/fpu_1db.bin tmp/fpnanrzdb.sim  #1800
./t4 -sv tbo/tbo/fpnotfiniterzdb.tbo   inp/inp/fpu_1db.bin tmp/fpnotfiniterzdb.sim  #1800
./t4 -sv tbo/tbo/fpintrzdb.tbo         inp/inp/fpu_1db.bin tmp/fpintrzdb.sim  #1800
./t4 -sv tbo/tbo/fpuchki32rzdb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki32rzdb.sim  #1800
./t4 -sv tbo/tbo/fpuchki64rzdb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki64rzdb.sim  #1800
./t4 -sv tbo/tbo/fprtoi32rzdb.tbo      inp/inp/fpu_1db.bin tmp/fprtoi32rzdb.sim  #1800

./t4 -sv tbo/tbo/fpduprpdb.tbo         inp/inp/fpu_1db.bin tmp/fpduprpdb.sim  #1800
./t4 -sv tbo/tbo/fprevrpdb.tbo         inp/inp/fpu_1db.bin tmp/fprevrpdb.sim  #1800
./t4 -sv tbo/tbo/fpurnrpdb.tbo         inp/inp/fpu_1db.bin tmp/fpurnrpdb.sim  #1800
./t4 -sv tbo/tbo/fpurzrpdb.tbo         inp/inp/fpu_1db.bin tmp/fpurzrpdb.sim  #1800
./t4 -sv tbo/tbo/fpurprpdb.tbo         inp/inp/fpu_1db.bin tmp/fpurprpdb.sim  #1800
./t4 -sv tbo/tbo/fpurmrpdb.tbo         inp/inp/fpu_1db.bin tmp/fpurmrpdb.sim  #1800
./t4 -sv tbo/tbo/fpaddrpdb.tbo         inp/inp/fpu_2db.bin tmp/fpaddrpdb.sim  #C0000
./t4 -sv tbo/tbo/fpsubrpdb.tbo         inp/inp/fpu_2db.bin tmp/fpsubrpdb.sim  #C0000
./t4 -sv tbo/tbo/fpmulrpdb.tbo         inp/inp/fpu_2db.bin tmp/fpmulrpdb.sim  #C0000
./t4 -sv tbo/tbo/fpdivrpdb.tbo         inp/inp/fpu_2db.bin tmp/fpdivrpdb.sim  #C0000
./t4 -sv tbo/tbo/fpuabsrpdb.tbo        inp/inp/fpu_1db.bin tmp/fpuabsrpdb.sim  #1800
./t4 -sv tbo/tbo/fpumulby2rpdb.tbo     inp/inp/fpu_1db.bin tmp/fpumulby2rpdb.sim    #1800
./t4 -sv tbo/tbo/fpudivby2rpdb.tbo     inp/inp/fpu_1db.bin tmp/fpudivby2rpdb.sim    #1800
./t4 -sv tbo/tbo/fpuexpinc32rpdb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpinc32rpdb.sim  #1800
./t4 -sv tbo/tbo/fpuexpdec32rpdb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpdec32rpdb.sim  #1800
./t4 -sv tbo/tbo/fpchkerrrpdb.tbo      inp/inp/fpu_1db.bin tmp/fpchkerrrpdb.sim     #1800
./t4 -sv tbo/tbo/fptesterrrpdb.tbo     inp/inp/fpu_1db.bin tmp/fptesterrrpdb.sim    #1800
./t4 -sv tbo/tbo/fpuseterrrpdb.tbo     inp/inp/fpu_1db.bin tmp/fpuseterrrpdb.sim    #1800
./t4 -sv tbo/tbo/fpuclrerrrpdb.tbo     inp/inp/fpu_1db.bin tmp/fpuclrerrrpdb.sim    #1800
./t4 -sv tbo/tbo/fpgtrpdb.tbo          inp/inp/fpu_2db.bin tmp/fpgtrpdb.sim        #C0000
./t4 -sv tbo/tbo/fpeqrpdb.tbo          inp/inp/fpu_2db.bin tmp/fpeqrpdb.sim        #C0000
./t4 -sv tbo/tbo/fporderedrpdb.tbo     inp/inp/fpu_2db.bin tmp/fporderedrpdb.sim   #C0000
./t4 -sv tbo/tbo/fpnanrpdb.tbo         inp/inp/fpu_1db.bin tmp/fpnanrpdb.sim        #1800
./t4 -sv tbo/tbo/fpnotfiniterpdb.tbo   inp/inp/fpu_1db.bin tmp/fpnotfiniterpdb.sim  #1800
./t4 -sv tbo/tbo/fpintrpdb.tbo         inp/inp/fpu_1db.bin tmp/fpintrpdb.sim        #1800
./t4 -sv tbo/tbo/fpuchki32rpdb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki32rpdb.sim    #1800
./t4 -sv tbo/tbo/fpuchki64rpdb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki64rpdb.sim    #1800
./t4 -sv tbo/tbo/fprtoi32rpdb.tbo      inp/inp/fpu_1db.bin tmp/fprtoi32rpdb.sim     #1800

./t4 -sv tbo/tbo/fpduprmdb.tbo         inp/inp/fpu_1db.bin tmp/fpduprmdb.sim        #1800
./t4 -sv tbo/tbo/fprevrmdb.tbo         inp/inp/fpu_1db.bin tmp/fprevrmdb.sim        #1800
./t4 -sv tbo/tbo/fpurnrmdb.tbo         inp/inp/fpu_1db.bin tmp/fpurnrmdb.sim        #1800
./t4 -sv tbo/tbo/fpurzrmdb.tbo         inp/inp/fpu_1db.bin tmp/fpurzrmdb.sim        #1800
./t4 -sv tbo/tbo/fpurprmdb.tbo         inp/inp/fpu_1db.bin tmp/fpurprmdb.sim        #1800
./t4 -sv tbo/tbo/fpurmrmdb.tbo         inp/inp/fpu_1db.bin tmp/fpurmrmdb.sim        #1800
./t4 -sv tbo/tbo/fpaddrmdb.tbo         inp/inp/fpu_2db.bin tmp/fpaddrmdb.sim       #C0000
./t4 -sv tbo/tbo/fpsubrmdb.tbo         inp/inp/fpu_2db.bin tmp/fpsubrmdb.sim       #C0000
./t4 -sv tbo/tbo/fpmulrmdb.tbo         inp/inp/fpu_2db.bin tmp/fpmulrmdb.sim       #C0000
./t4 -sv tbo/tbo/fpdivrmdb.tbo         inp/inp/fpu_2db.bin tmp/fpdivrmdb.sim       #C0000
./t4 -sv tbo/tbo/fpuabsrmdb.tbo        inp/inp/fpu_1db.bin tmp/fpuabsrmdb.sim       #1800
./t4 -sv tbo/tbo/fpumulby2rmdb.tbo     inp/inp/fpu_1db.bin tmp/fpumulby2rmdb.sim    #1800
./t4 -sv tbo/tbo/fpudivby2rmdb.tbo     inp/inp/fpu_1db.bin tmp/fpudivby2rmdb.sim    #1800
./t4 -sv tbo/tbo/fpuexpinc32rmdb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpinc32rmdb.sim  #1800
./t4 -sv tbo/tbo/fpuexpdec32rmdb.tbo   inp/inp/fpu_1db.bin tmp/fpuexpdec32rmdb.sim  #1800
./t4 -sv tbo/tbo/fpchkerrrmdb.tbo      inp/inp/fpu_1db.bin tmp/fpchkerrrmdb.sim     #1800
./t4 -sv tbo/tbo/fptesterrrmdb.tbo     inp/inp/fpu_1db.bin tmp/fptesterrrmdb.sim    #1800
./t4 -sv tbo/tbo/fpuseterrrmdb.tbo     inp/inp/fpu_1db.bin tmp/fpuseterrrmdb.sim    #1800
./t4 -sv tbo/tbo/fpuclrerrrmdb.tbo     inp/inp/fpu_1db.bin tmp/fpuclrerrrmdb.sim    #1800
./t4 -sv tbo/tbo/fpgtrmdb.tbo          inp/inp/fpu_2db.bin tmp/fpgtrmdb.sim        #C0000
./t4 -sv tbo/tbo/fpeqrmdb.tbo          inp/inp/fpu_2db.bin tmp/fpeqrmdb.sim        #C0000
./t4 -sv tbo/tbo/fporderedrmdb.tbo     inp/inp/fpu_2db.bin tmp/fporderedrmdb.sim   #C0000
./t4 -sv tbo/tbo/fpnanrmdb.tbo         inp/inp/fpu_1db.bin tmp/fpnanrmdb.sim        #1800
./t4 -sv tbo/tbo/fpnotfinitermdb.tbo   inp/inp/fpu_1db.bin tmp/fpnotfinitermdb.sim  #1800
./t4 -sv tbo/tbo/fpintrmdb.tbo         inp/inp/fpu_1db.bin tmp/fpintrmdb.sim        #1800
./t4 -sv tbo/tbo/fpuchki32rmdb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki32rmdb.sim    #1800
./t4 -sv tbo/tbo/fpuchki64rmdb.tbo     inp/inp/fpu_1db.bin tmp/fpuchki64rmdb.sim    #1800
./t4 -sv tbo/tbo/fprtoi32rmdb.tbo      inp/inp/fpu_1db.bin tmp/fprtoi32rmdb.sim     #1800

./t4 -sv tbo/tbo/fpur64tor32__db.tbo   inp/inp/fpu_1db.bin tmp/fpur64tor32__db.sim  #1800
./t4 -sv tbo/tbo/fpur64tor32rndb.tbo   inp/inp/fpu_1db.bin tmp/fpur64tor32rndb.sim  #1800
./t4 -sv tbo/tbo/fpur64tor32rzdb.tbo   inp/inp/fpu_1db.bin tmp/fpur64tor32rzdb.sim  #1800
./t4 -sv tbo/tbo/fpur64tor32rpdb.tbo   inp/inp/fpu_1db.bin tmp/fpur64tor32rpdb.sim  #1800
./t4 -sv tbo/tbo/fpur64tor32rmdb.tbo   inp/inp/fpu_1db.bin tmp/fpur64tor32rmdb.sim  #1800
./t4 -sv tbo/tbo/fpunoround__db.tbo    inp/inp/fpu_1db.bin tmp/fpunoround__db.sim   #1800
./t4 -sv tbo/tbo/fpunoroundrndb.tbo    inp/inp/fpu_1db.bin tmp/fpunoroundrndb.sim   #1800
./t4 -sv tbo/tbo/fpunoroundrzdb.tbo    inp/inp/fpu_1db.bin tmp/fpunoroundrzdb.sim   #1800
./t4 -sv tbo/tbo/fpunoroundrpdb.tbo    inp/inp/fpu_1db.bin tmp/fpunoroundrpdb.sim   #1800
./t4 -sv tbo/tbo/fpunoroundrmdb.tbo    inp/inp/fpu_1db.bin tmp/fpunoroundrmdb.sim   #1800
./t4 -sv tbo/tbo/fpldzerodb__db.tbo    inp/inp/fpu_1db.bin tmp/fpldzerodb__db.sim   #1800
./t4 -sv tbo/tbo/fpldzerodbrndb.tbo    inp/inp/fpu_1db.bin tmp/fpldzerodbrndb.sim   #1800
./t4 -sv tbo/tbo/fpldzerodbrzdb.tbo    inp/inp/fpu_1db.bin tmp/fpldzerodbrzdb.sim   #1800
./t4 -sv tbo/tbo/fpldzerodbrpdb.tbo    inp/inp/fpu_1db.bin tmp/fpldzerodbrpdb.sim   #1800
./t4 -sv tbo/tbo/fpldzerodbrmdb.tbo    inp/inp/fpu_1db.bin tmp/fpldzerodbrmdb.sim   #1800
./t4 -sv tbo/tbo/fpusqrt__db.tbo       inp/inp/fpu_1db.bin tmp/fpusqrt__db.sim      #1800
./t4 -sv tbo/tbo/fpusqrtrndb.tbo       inp/inp/fpu_1db.bin tmp/fpusqrtrndb.sim      #1800
./t4 -sv tbo/tbo/fpusqrtrzdb.tbo       inp/inp/fpu_1db.bin tmp/fpusqrtrzdb.sim      #1800
./t4 -sv tbo/tbo/fpusqrtrpdb.tbo       inp/inp/fpu_1db.bin tmp/fpusqrtrpdb.sim      #1800
./t4 -sv tbo/tbo/fpusqrtrmdb.tbo       inp/inp/fpu_1db.bin tmp/fpusqrtrmdb.sim      #1800

./t4 -sv tbo/tbo/fpb32tor64__db.tbo    inp/inp/fpumidb.bin tmp/fpb32tor64__db.sim   #4000
./t4 -sv tbo/tbo/fpi32tor64__db.tbo    inp/inp/fpumidb.bin tmp/fpi32tor64__db.sim   #4000
./t4 -sv tbo/tbo/fpldnldb__db.tbo      inp/inp/fpum1db.bin tmp/fpldnldb__db.sim     #2000
./t4 -sv tbo/tbo/fpldnldbi__db.tbo     inp/inp/fpum1db.bin tmp/fpldnldbi__db.sim    #2000
./t4 -sv tbo/tbo/fpldnladddb__db.tbo   inp/inp/fpum2db.bin tmp/fpldnladddb__db.sim #100000
./t4 -sv tbo/tbo/fpldnlmuldb__db.tbo   inp/inp/fpum2db.bin tmp/fpldnlmuldb__db.sim #100000
./t4 -sv tbo/tbo/fpstnldb__db.tbo      inp/inp/fpum1db.bin tmp/fpstnldb__db.sim     #2000
./t4 -sv tbo/tbo/fpstnli32__db.tbo     inp/inp/fpum1db.bin tmp/fpstnli32__db.sim    #2000
./t4 -sv tbo/tbo/fpb32tor64rndb.tbo    inp/inp/fpumidb.bin tmp/fpb32tor64rndb.sim   #4000
./t4 -sv tbo/tbo/fpi32tor64rndb.tbo    inp/inp/fpumidb.bin tmp/fpi32tor64rndb.sim   #4000
./t4 -sv tbo/tbo/fpldnldbrndb.tbo      inp/inp/fpum1db.bin tmp/fpldnldbrndb.sim     #2000
./t4 -sv tbo/tbo/fpldnldbirndb.tbo     inp/inp/fpum1db.bin tmp/fpldnldbirndb.sim    #2000
./t4 -sv tbo/tbo/fpldnladddbrndb.tbo   inp/inp/fpum2db.bin tmp/fpldnladddbrndb.sim #100000
./t4 -sv tbo/tbo/fpldnlmuldbrndb.tbo   inp/inp/fpum2db.bin tmp/fpldnlmuldbrndb.sim #100000
./t4 -sv tbo/tbo/fpstnldbrndb.tbo      inp/inp/fpum1db.bin tmp/fpstnldbrndb.sim     #2000
./t4 -sv tbo/tbo/fpstnli32rndb.tbo     inp/inp/fpum1db.bin tmp/fpstnli32rndb.sim    #2000
./t4 -sv tbo/tbo/fpb32tor64rzdb.tbo    inp/inp/fpumidb.bin tmp/fpb32tor64rzdb.sim   #4000
./t4 -sv tbo/tbo/fpi32tor64rzdb.tbo    inp/inp/fpumidb.bin tmp/fpi32tor64rzdb.sim   #4000
./t4 -sv tbo/tbo/fpldnldbrzdb.tbo      inp/inp/fpum1db.bin tmp/fpldnldbrzdb.sim     #2000
./t4 -sv tbo/tbo/fpldnldbirzdb.tbo     inp/inp/fpum1db.bin tmp/fpldnldbirzdb.sim    #2000
./t4 -sv tbo/tbo/fpldnladddbrzdb.tbo   inp/inp/fpum2db.bin tmp/fpldnladddbrzdb.sim #100000
./t4 -sv tbo/tbo/fpldnlmuldbrzdb.tbo   inp/inp/fpum2db.bin tmp/fpldnlmuldbrzdb.sim #100000
./t4 -sv tbo/tbo/fpstnldbrzdb.tbo      inp/inp/fpum1db.bin tmp/fpstnldbrzdb.sim     #2000
./t4 -sv tbo/tbo/fpstnli32rzdb.tbo     inp/inp/fpum1db.bin tmp/fpstnli32rzdb.sim    #2000
./t4 -sv tbo/tbo/fpb32tor64rpdb.tbo    inp/inp/fpumidb.bin tmp/fpb32tor64rpdb.sim   #4000
./t4 -sv tbo/tbo/fpi32tor64rpdb.tbo    inp/inp/fpumidb.bin tmp/fpi32tor64rpdb.sim   #4000
./t4 -sv tbo/tbo/fpldnldbrpdb.tbo      inp/inp/fpum1db.bin tmp/fpldnldbrpdb.sim     #2000
./t4 -sv tbo/tbo/fpldnldbirpdb.tbo     inp/inp/fpum1db.bin tmp/fpldnldbirpdb.sim    #2000
./t4 -sv tbo/tbo/fpldnladddbrpdb.tbo   inp/inp/fpum2db.bin tmp/fpldnladddbrpdb.sim #100000
./t4 -sv tbo/tbo/fpldnlmuldbrpdb.tbo   inp/inp/fpum2db.bin tmp/fpldnlmuldbrpdb.sim #100000
./t4 -sv tbo/tbo/fpstnldbrpdb.tbo      inp/inp/fpum1db.bin tmp/fpstnldbrpdb.sim     #2000
./t4 -sv tbo/tbo/fpstnli32rpdb.tbo     inp/inp/fpum1db.bin tmp/fpstnli32rpdb.sim    #2000
./t4 -sv tbo/tbo/fpb32tor64rmdb.tbo    inp/inp/fpumidb.bin tmp/fpb32tor64rmdb.sim   #4000
./t4 -sv tbo/tbo/fpi32tor64rmdb.tbo    inp/inp/fpumidb.bin tmp/fpi32tor64rmdb.sim   #4000
./t4 -sv tbo/tbo/fpldnldbrmdb.tbo      inp/inp/fpum1db.bin tmp/fpldnldbrmdb.sim     #2000
./t4 -sv tbo/tbo/fpldnldbirmdb.tbo     inp/inp/fpum1db.bin tmp/fpldnldbirmdb.sim    #2000
./t4 -sv tbo/tbo/fpldnladddbrmdb.tbo   inp/inp/fpum2db.bin tmp/fpldnladddbrmdb.sim #100000
./t4 -sv tbo/tbo/fpldnlmuldbrmdb.tbo   inp/inp/fpum2db.bin tmp/fpldnlmuldbrmdb.sim #100000
./t4 -sv tbo/tbo/fpstnldbrmdb.tbo      inp/inp/fpum1db.bin tmp/fpstnldbrmdb.sim     #2000
./t4 -sv tbo/tbo/fpstnli32rmdb.tbo     inp/inp/fpum1db.bin tmp/fpstnli32rmdb.sim    #2000
